//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.SpravochnikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spravochnik
    {
        public int id { get; set; }
        public string FamilyName { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public string Telephone { get; set; }
        public byte[] Photo { get; set; }
        public string Category { get; set; }
    }
}
